# Generated by Django 3.2.9 on 2022-06-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSala', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
