# Generated by Django 3.2.9 on 2022-06-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersonal', models.CharField(max_length=20, verbose_name='nombre del personal')),
                ('apellidosPersonal', models.CharField(max_length=20, verbose_name='apellidos del personal')),
                ('asignacion', models.CharField(max_length=20, verbose_name='asignacion sala')),
                ('hora', models.CharField(max_length=20, verbose_name='hora')),
                ('dia', models.CharField(max_length=20, verbose_name='hora')),
            ],
        ),
        migrations.AlterField(
            model_name='estadoaula',
            name='nombreSala',
            field=models.CharField(max_length=20, verbose_name='nombre de sala'),
        ),
    ]
