# Generated by Django 3.2.9 on 2022-06-18 00:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0002_auto_20220611_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria Desactivada')),
                ('imagen', models.ImageField(null=True, upload_to='img')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.AlterField(
            model_name='estadoaula',
            name='nombreSala',
            field=models.CharField(max_length=40, verbose_name='nombre de sala'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='asignacion',
            field=models.CharField(max_length=40, verbose_name='asignacion sala'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=20, verbose_name='dia'),
        ),
    ]
