# Generated by Django 3.2.9 on 2022-06-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0003_auto_20220617_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
