# Generated by Django 3.2.9 on 2022-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0005_alter_publicacion_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
