# Generated by Django 3.2.9 on 2022-06-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0006_alter_publicacion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='observacion detectada'),
        ),
    ]
