# Generated by Django 3.2.9 on 2022-06-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0007_horario_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='descarga', verbose_name='Archivo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
            ],
        ),
    ]
