# Generated by Django 3.2.9 on 2022-06-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0008_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoaula',
            name='aforo',
            field=models.CharField(default=1, max_length=30, verbose_name='Aforo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadoaula',
            name='sector',
            field=models.CharField(default=2, max_length=30, verbose_name='Sector'),
            preserve_default=False,
        ),
    ]
