# Generated by Django 3.2.9 on 2022-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0009_auto_20220621_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='estadoaula',
            name='aforo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Aforo'),
        ),
        migrations.AlterField(
            model_name='estadoaula',
            name='sector',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
