# Generated by Django 3.2.9 on 2022-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0010_auto_20220621_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=40, verbose_name='dia'),
        ),
    ]
