# Generated by Django 3.2.9 on 2022-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0012_registroincidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroincidencia',
            name='estado',
            field=models.CharField(default=1, max_length=20, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
