# Generated by Django 3.2.9 on 2022-08-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0013_registroincidencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='nombre del afectado')),
                ('nombrePersonal', models.CharField(max_length=20, verbose_name='nombre del registrante')),
                ('apellidosPersoal', models.CharField(max_length=20, verbose_name='apellidos del registrante')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('hora', models.TimeField(null=True, verbose_name='Fecha')),
                ('cantidadAlmacenada', models.IntegerField(null=True, verbose_name='Fecha')),
                ('cantidadUtilizada', models.IntegerField(null=True, verbose_name='Fecha')),
                ('producto', models.CharField(max_length=20, verbose_name='nombre del afectado')),
            ],
        ),
        migrations.AlterField(
            model_name='registroincidencia',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
