# Generated by Django 3.2.9 on 2022-08-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0014_auto_20220804_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersonal', models.CharField(blank=True, max_length=20, verbose_name='nombre del registrante')),
                ('apellidosPersoal', models.CharField(blank=True, max_length=20, verbose_name='apellidos del registrante')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, verbose_name='Hora')),
                ('cantidadUtilizada', models.IntegerField(blank=True, verbose_name='Cantidad utilizada')),
                ('producto', models.CharField(blank=True, max_length=20, verbose_name='Producto utilizado')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='apellidosPersoal',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='cantidadUtilizada',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='nombrePersonal',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidadAlmacenada',
            field=models.IntegerField(null=True, verbose_name='Cantidad almacenada'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombreProducto',
            field=models.CharField(max_length=20, verbose_name='Producto'),
        ),
    ]
