# Generated by Django 3.2.9 on 2022-08-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0015_auto_20220804_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retiroinventario',
            old_name='apellidosPersoal',
            new_name='apellidosPersonal',
        ),
    ]
