# Generated by Django 3.2.9 on 2022-08-08 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0016_rename_apellidospersoal_retiroinventario_apellidospersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidadAlmacenada',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad almacenada'),
        ),
        migrations.AlterField(
            model_name='retiroinventario',
            name='cantidadUtilizada',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad utilizada'),
        ),
    ]
