# Generated by Django 3.2.9 on 2022-08-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0017_auto_20220807_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('largoGeneral', models.IntegerField(verbose_name='Largo de sala')),
                ('anchoGeneral', models.IntegerField(verbose_name='Ancho de sala')),
                ('largoDemarcacion', models.IntegerField(verbose_name='Largo de demarcacion')),
                ('anchoDemarcacion', models.IntegerField(verbose_name='Ancho de demarcacion')),
                ('resultado', models.IntegerField(blank=True, verbose_name='resultado')),
            ],
        ),
    ]
