# Generated by Django 3.2.9 on 2022-08-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0018_aforo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aforo',
            name='resultado',
            field=models.IntegerField(blank=True, null=True, verbose_name='resultado'),
        ),
    ]
