# Generated by Django 3.2.9 on 2022-08-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0019_alter_aforo_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.DateField(verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(verbose_name='hora'),
        ),
    ]
