# Generated by Django 3.2.9 on 2022-09-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAulasApp', '0020_auto_20220812_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aforo',
            name='anchoDemarcacion',
            field=models.PositiveIntegerField(verbose_name='Ancho de demarcacion'),
        ),
        migrations.AlterField(
            model_name='aforo',
            name='anchoGeneral',
            field=models.PositiveIntegerField(verbose_name='Ancho de sala'),
        ),
        migrations.AlterField(
            model_name='aforo',
            name='largoDemarcacion',
            field=models.PositiveIntegerField(verbose_name='Largo de demarcacion'),
        ),
        migrations.AlterField(
            model_name='aforo',
            name='largoGeneral',
            field=models.PositiveIntegerField(verbose_name='Largo de sala'),
        ),
        migrations.AlterField(
            model_name='aforo',
            name='resultado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombreProducto',
            field=models.CharField(max_length=50, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retiroinventario',
            name='producto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Producto utilizado'),
        ),
    ]
